// The player's own words in the episode's language (the episode's text comes from the backend in that language).
const EN = {
  presenter: 'Presenter',
  analyst: 'Analyst',
  soundOff: 'Sound off',
  soundOn: 'Sound on',
  soundOffTip: 'Sound is off: captions only. Turn on the narration.',
  soundOnTip: 'Turn the narration off',
  end: 'End of episode',
  again: 'Watch again',
  another: 'Another episode',
  close: 'Close',
  next: 'Next',
  chipGemini: 'Made by a Gemini agent',
  chipFallback: 'Fallback script',
  chipTemplate: 'Template script',
  elevenVoice: 'ElevenLabs voice',
  browserVoice: 'Browser voice',
  today: 'today',
  reserveNote: "Past the power plants' reserve line: also needs new plants or flexible campuses",
  source: 'Source',
  checkedBy: 'Gemini wrote this',
  checkedFacts: (n) => `${n} ${n === 1 ? 'fact' : 'facts'} checked`,
  checkedNone: 'checked',
  rewritten: 'fixed after the checker sent a draft back',
  plainScript: 'Plain script',
}
const ES = {
  presenter: 'Presentador',
  analyst: 'Analista',
  soundOff: 'Sonido apagado',
  soundOn: 'Sonido encendido',
  soundOffTip: 'El sonido está apagado: solo subtítulos. Activa la narración.',
  soundOnTip: 'Apagar la narración',
  end: 'Fin del episodio',
  again: 'Ver de nuevo',
  another: 'Otro episodio',
  close: 'Cerrar',
  next: 'Siguiente',
  chipGemini: 'Hecho por un agente de Gemini',
  chipFallback: 'Guion de respaldo',
  chipTemplate: 'Guion de plantilla',
  elevenVoice: 'Voz de ElevenLabs',
  browserVoice: 'Voz del navegador',
  today: 'hoy',
  reserveNote: 'Pasada la línea de reserva de las centrales: también hacen falta nuevas centrales o campus flexibles',
  source: 'Fuente',
  checkedBy: 'Lo escribió Gemini',
  checkedFacts: (n) => `${n} ${n === 1 ? 'dato comprobado' : 'datos comprobados'}`,
  checkedNone: 'comprobado',
  rewritten: 'corregido tras la revisión',
  plainScript: 'Guion base',
}

export const wordsFor = (lang) => (lang === 'es' ? ES : EN)
