// The play-by-play show's own words, EN and ES (the deck's words come from the backend; these label the
// animated parts: the scoreboard, the play cards, the options, the ticker). Every figure is an estimate on
// a synthetic grid model, and the words say so.

export const S = {
  en: {
    live: 'On air',
    paused: 'Paused',
    tollCost: 'Expected cost',
    tollTime: 'Time without power',
    tollTimeNote: 'Fast-forward to the average outage (estimate)',
    tollPeople: 'People without power',
    hoursShort: 'h',
    minShort: 'min',
    range: 'Range',
    playByPlay: 'Play-by-play',
    play: 'Play',
    of: 'of',
    transformer: 'Transformer',
    line: 'Line',
    storm: 'Storm',
    ofItsLimit: 'of its limit',
    lose: 'without power',
    hit: 'hit',
    plus: '+',
    scoreboard: 'Scoreboard',
    scPeople: 'People hit (estimate)',
    scMw: 'MW lost',
    scLines: 'Lines down',
    scHospitals: 'Hospitals in the dark',
    infra: 'Crucial infrastructure',
    infraDown: 'down',
    hospitalsDark: (n) => `${n} ${n === 1 ? 'hospital' : 'hospitals'} on backup power`,
    subsDark: (n) => `${n} ${n === 1 ? 'substation' : 'substations'} dark`,
    calloutTransformer: 'Transformer down',
    calloutLine: 'Line down',
    calloutDark: 'Lights out',
    calloutHospitals: 'Hospitals on backup power',
    calloutStorm: 'Storm damage',
    theProblem: 'The problem',
    slateSub: 'What the grid cannot carry',
    problemPeople: 'People without power',
    problemCost: 'Expected cost',
    problemMw: 'MW of load lost',
    problemHours: 'Time without power',
    problemLines: 'Lines tripped',
    solutions: 'Solutions',
    option: 'Option',
    toBuild: (mw) => `To build ${mw} MW here you have to:`,
    toKeep: 'To keep the grid up you have to:',
    rerun: 'Re-run on the model',
    peopleOut: 'People without power',
    zeroOut: '0 people lose power',
    peopleOutN: (n) => `${n} people still lose power`,
    verifiedEngine: 'Engine-verified',
    verifiedAI: 'AI-proposed, engine-verified',
    aiPlan: 'AI plan',
    haveTo: (mw, where) => `To build ${mw} MW${where ? ` at ${where}` : ''}, you have to do one of these`,
    haveToMulti: (n, mw) => `To build these ${n} campuses (${mw} MW in all), you have to do one of these`,
    haveToKeep: 'To keep the lights on, you have to do one of these',
    costHigh: (v) => `Estimated cost: up to ${v}`,
    costHighNote: 'high end of the estimate',
    fullSize: 'Full size',
    aiFound: (asked, verified) => `AI proposed ${asked} ${asked === 1 ? 'plan' : 'plans'}; the engine re-ran each one and verified ${verified}.`,
    engineFound: (n) => `The engine re-ran every fix on the model: ${n} ${n === 1 ? 'holds' : 'hold'}.`,
    aiThinking: 'AI is proposing more plans; the engine checks each one…',
    frame: 'AI finds the fixes. The physics engine verifies every one.',
    costBar: 'Cost (high end)',
    keptBar: 'Campus kept',
    sayPlan: (k, n, name, keep) => `Option ${k} of ${n}: ${name}. ${keep} If you want to build it here, you have to do this.`,
    sayKeepAll: (mw) => `It keeps all ${mw} MW.`,
    sayKeep: (mw, of) => `It keeps ${mw} of the ${of} MW.`,
    sayResult0: 'Re-run on the model: 0 people lose power.',
    sayResultN: (n) => `Re-run on the model: ${n} people still lose power.`,
    partly: 'Partly verified: not everyone keeps power',
    keeps: 'Campus kept',
    costLabel: 'Estimated cost',
    costNone: 'Cost not estimated',
    bottomLine: 'Bottom line',
    compared: 'The options, compared',
    bestPick: 'Best pick',
    kept: 'kept',
    noFixWhy: 'No fix reaches them',
    restore: 'Restore in this order',
    lightsBack: 'people back (estimate)',
    aTicker: 'Live facts',
    simTicker: 'SIMULATION · synthetic grid model · every people and cost figure is an estimate',
    campusShare: 'of the first line’s flow is the data center',
    withCampus: 'With the data center',
    withoutCampus: 'Without it',
    limit: 'Limit',
    rank: (n) => `Option ${n}`,
  },
  es: {
    live: 'En vivo',
    paused: 'En pausa',
    tollCost: 'Costo esperado',
    tollTime: 'Tiempo sin luz',
    tollTimeNote: 'Avance rápido hasta el apagón promedio (estimación)',
    tollPeople: 'Personas sin electricidad',
    hoursShort: 'h',
    minShort: 'min',
    range: 'Rango',
    playByPlay: 'Jugada a jugada',
    play: 'Jugada',
    of: 'de',
    transformer: 'Transformador',
    line: 'Línea',
    storm: 'Tormenta',
    ofItsLimit: 'de su límite',
    lose: 'sin luz',
    hit: 'afectadas',
    plus: '+',
    scoreboard: 'Marcador',
    scPeople: 'Personas afectadas (estimación)',
    scMw: 'MW perdidos',
    scLines: 'Líneas caídas',
    scHospitals: 'Hospitales a oscuras',
    infra: 'Infraestructura crítica',
    infraDown: 'caída',
    hospitalsDark: (n) => `${n} ${n === 1 ? 'hospital' : 'hospitales'} con energía de respaldo`,
    subsDark: (n) => `${n} ${n === 1 ? 'subestación' : 'subestaciones'} a oscuras`,
    calloutTransformer: 'Transformador caído',
    calloutLine: 'Línea caída',
    calloutDark: 'Apagón',
    calloutHospitals: 'Hospitales con energía de respaldo',
    calloutStorm: 'Daño de la tormenta',
    theProblem: 'El problema',
    slateSub: 'Lo que la red no puede soportar',
    problemPeople: 'Personas sin luz',
    problemCost: 'Costo esperado',
    problemMw: 'MW de carga perdidos',
    problemHours: 'Tiempo sin luz',
    problemLines: 'Líneas disparadas',
    solutions: 'Soluciones',
    option: 'Opción',
    toBuild: (mw) => `Para construir ${mw} MW aquí hay que:`,
    toKeep: 'Para mantener la red en pie hay que:',
    rerun: 'Simulada de nuevo',
    peopleOut: 'Personas sin luz',
    zeroOut: '0 personas pierden la luz',
    peopleOutN: (n) => `${n} personas aún pierden la luz`,
    verifiedEngine: 'Verificada por el motor',
    verifiedAI: 'Propuesta por IA, verificada por el motor',
    aiPlan: 'Plan de IA',
    haveTo: (mw, where) => `Para construir ${mw} MW${where ? ` en ${where}` : ''}, tienes que hacer una de estas`,
    haveToMulti: (n, mw) => `Para construir estos ${n} campus (${mw} MW en total), tienes que hacer una de estas`,
    haveToKeep: 'Para mantener la luz, tienes que hacer una de estas',
    costHigh: (v) => `Costo estimado: hasta ${v}`,
    costHighNote: 'extremo alto de la estimación',
    fullSize: 'Tamaño completo',
    aiFound: (asked, verified) => `La IA propuso ${asked} ${asked === 1 ? 'plan' : 'planes'}; el motor simuló cada uno y verificó ${verified}.`,
    engineFound: (n) => `El motor simuló cada solución en el modelo: ${n} ${n === 1 ? 'funciona' : 'funcionan'}.`,
    aiThinking: 'La IA está proponiendo más planes; el motor comprueba cada uno…',
    frame: 'La IA encuentra las soluciones. El motor físico verifica cada una.',
    costBar: 'Costo (extremo alto)',
    keptBar: 'Campus conservado',
    sayPlan: (k, n, name, keep) => `Opción ${k} de ${n}: ${name}. ${keep} Si quieres construirlo aquí, tienes que hacer esto.`,
    sayKeepAll: (mw) => `Conserva los ${mw} MW completos.`,
    sayKeep: (mw, of) => `Conserva ${mw} de los ${of} MW.`,
    sayResult0: 'Simulada de nuevo: 0 personas pierden la luz.',
    sayResultN: (n) => `Simulada de nuevo: ${n} personas siguen sin luz.`,
    partly: 'Verificada en parte: no todos mantienen la luz',
    keeps: 'Campus conservado',
    costLabel: 'Costo estimado',
    costNone: 'Costo sin estimar',
    bottomLine: 'Conclusión',
    compared: 'Las opciones, comparadas',
    bestPick: 'La mejor',
    kept: 'conservado',
    noFixWhy: 'Ninguna solución los alcanza',
    restore: 'Restablecer en este orden',
    lightsBack: 'personas recuperan la luz (estimación)',
    aTicker: 'Datos en vivo',
    simTicker: 'SIMULACRO · modelo sintético de la red · toda cifra de personas y costos es una estimación',
    campusShare: 'del flujo de la primera línea es el centro de datos',
    withCampus: 'Con el centro de datos',
    withoutCampus: 'Sin él',
    limit: 'Límite',
    rank: (n) => `Opción ${n}`,
  },
}

// What each option asks for ("you have to ..."), by family; the engine's own list (option.must) wins.
export const MUST = {
  en: {
    upgrade: (l) => `Upgrade ${l.label}: ${Math.round(l.old_mva).toLocaleString('en-US')} to ${Math.round(l.new_mva).toLocaleString('en-US')} MVA`,
    shrink: (from, to) => [`Cut the campus from ${from} MW to ${to} MW`, `Accept about ${Math.round((to / from) * 100)}% of the planned size`],
    move: (town) => [`Build it at a ${town} substation instead`, 'Use a site with room on its lines'],
    flexible: (mw) => [`Agree to curtail to ${mw} MW at the peak`, 'Run at full size in the quieter hours'],
    onsite: (gen, net) => [`Add ${gen} MW of on-site generation`, `Let the grid supply only ${net} MW`],
    combo: (mw) => [`Shrink the campus to ${mw} MW`],
    remove: () => ['Do not build the data center at this site'],
  },
  es: {
    upgrade: (l) => `Mejorar ${l.label.replace(/^the /, '')}: ${Math.round(l.old_mva).toLocaleString('en-US')} a ${Math.round(l.new_mva).toLocaleString('en-US')} MVA`,
    shrink: (from, to) => [`Reducir el campus de ${from} MW a ${to} MW`, `Aceptar cerca del ${Math.round((to / from) * 100)}% del tamaño planeado`],
    move: (town) => [`Construirlo en una subestación de ${town}`, 'Usar un sitio con espacio en sus líneas'],
    flexible: (mw) => [`Aceptar recortar a ${mw} MW en el pico`, 'Operar a tamaño completo en las horas tranquilas'],
    onsite: (gen, net) => [`Añadir ${gen} MW de generación propia`, `Que la red suministre solo ${net} MW`],
    combo: (mw) => [`Reducir el campus a ${mw} MW`],
    remove: () => ['No construir el centro de datos en este sitio'],
  },
}

export const OPTION_NAME = {
  en: {
    upgrade: (mw) => `Strengthen the grid, keep all ${mw} MW`,
    shrink: (mw) => `Build smaller: ${mw} MW`,
    move: () => 'Build it somewhere with room',
    flexible: (mw) => `Make it flexible: curtail to ${mw} MW at the peak`,
    onsite: (gen) => `Generate ${gen} MW on site`,
    combo: (mw) => `Build ${mw} MW and upgrade the weak link`,
    agentic: () => 'AI plan: strengthen the grid',
    remove: () => 'Do not build it here',
    other: () => 'Another fix',
  },
  es: {
    upgrade: (mw) => `Reforzar la red y mantener los ${mw} MW`,
    shrink: (mw) => `Construir más pequeño: ${mw} MW`,
    move: () => 'Construirlo donde haya espacio',
    flexible: (mw) => `Hacerlo flexible: recortar a ${mw} MW en el pico`,
    onsite: (gen) => `Generar ${gen} MW en el sitio`,
    combo: (mw) => `Construir ${mw} MW y reforzar el punto débil`,
    agentic: () => 'Plan de IA: reforzar la red',
    remove: () => 'No construirlo aquí',
    other: () => 'Otra solución',
  },
}
