// The play-by-play show's own words, EN and ES (the deck's words come from the backend; these label the
// animated parts: the scoreboard, the play cards, the options, the ticker). Every figure is an estimate on
// a synthetic grid model, and the words say so.

export const S = {
  en: {
    live: 'On air',
    paused: 'Paused',
    tollCost: 'Expected cost',
    tollTime: 'Time without power',
    tollTimeNote: 'Fast-forward to the average outage (estimate)',
    tollPeople: 'People without power',
    hoursShort: 'h',
    minShort: 'min',
    range: 'Range',
    playByPlay: 'Play-by-play',
    play: 'Play',
    of: 'of',
    transformer: 'Transformer',
    line: 'Line',
    storm: 'Storm',
    ofItsLimit: 'of its limit',
    lose: 'without power',
    hit: 'hit',
    plus: '+',
    scoreboard: 'Scoreboard',
    scPeople: 'People hit (estimate)',
    scMw: 'MW lost',
    scLines: 'Lines down',
    scHospitals: 'Hospitals in dark areas',
    step: 'Step',
    farPast: 'far past its limit',
    farShort: '>300%',
    restHead: 'Beyond those',
    restCard: (n) => `${n} more`,
    infra: 'Crucial infrastructure',
    infraDown: 'down',
    hospitalsDark: (n) => `${n} ${n === 1 ? 'hospital' : 'hospitals'} in dark areas (assumed on backup)`,
    subsDark: (n) => `${n} ${n === 1 ? 'substation' : 'substations'} dark`,
    calloutTransformer: 'Transformer down',
    calloutLine: 'Line down',
    calloutDark: 'Lights out',
    calloutHospitals: 'Hospitals in dark areas (assumed on backup)',
    calloutStorm: 'Storm damage',
    theProblem: 'The problem',
    slateSub: 'What the grid cannot carry',
    problemPeople: 'People without power',
    problemCost: 'Expected cost',
    problemMw: 'MW of load lost',
    problemHours: 'Time without power',
    problemLines: 'Lines tripped',
    solutions: 'Solutions',
    option: 'Option',
    toBuild: (mw) => `To build ${mw} MW here you have to:`,
    toKeep: 'To keep the grid up you have to:',
    rerun: 'Re-run on the model',
    peopleOut: 'People without power',
    zeroOut: '0 people lose power',
    peopleOutN: (n) => `${n} people still lose power`,
    verifiedEngine: 'Engine-verified',
    verifiedAI: 'AI-proposed, engine-verified',
    aiPlan: 'AI plan',
    haveTo: (mw, where) => `To build ${mw} MW${where ? ` at ${where}` : ''}, you have to do one of these`,
    haveToMulti: (n, mw) => `To build these ${n} campuses (${mw} MW in all), you have to do one of these`,
    haveToKeep: 'To keep the lights on, you have to do one of these',
    costHigh: (v) => `Estimated cost: up to ${v}`,
    costHighNote: 'high end of the estimate',
    fullSize: 'Full size',
    aiFound: (asked, verified) => `AI proposed ${asked} ${asked === 1 ? 'plan' : 'plans'}; the engine re-ran each one and verified ${verified}.`,
    engineFound: (n) => `The engine re-ran every fix on the model: ${n} ${n === 1 ? 'holds' : 'hold'}.`,
    aiThinking: 'AI is proposing more plans; the engine checks each one…',
    frame: 'AI finds the fixes. The physics engine verifies every one.',
    aiWork: 'Watch the AI work',
    aiWorkHead: 'How the AI found them: it proposes, the engine re-runs, it revises',
    aiWorkHead1: 'How the AI found them: it proposes, the engine re-runs every plan',
    aiWorkCount: (asked, verified, rounds) => `${asked} ${asked === 1 ? 'plan' : 'plans'} · ${verified} verified · ${rounds} ${rounds === 1 ? 'round' : 'rounds'}`,
    aiWorkSay: (asked, verified, rounds) => `How the AI found them: Gemini proposed ${asked} ${asked === 1 ? 'plan' : 'plans'} in ${rounds} ${rounds === 1 ? 'round' : 'rounds'}. The engine re-ran every one${rounds > 1 ? ', sent back what still failed,' : ''} and verified ${verified}.`,
    costBar: 'Cost (high end)',
    keptBar: 'Campus kept',
    sayPlan: (k, n, name, keep) => `Option ${k} of ${n}: ${name}. ${keep} If you want to build it here, you have to do this.`,
    sayKeepAll: (mw) => `It keeps all ${mw} MW.`,
    sayKeep: (mw, of) => `It keeps ${mw} of the ${of} MW.`,
    sayFlexKeep: (mw, except) => `It runs all ${mw} MW except ${except || 'at the peak'}, with no new equipment.`,
    sayOnsiteKeep: (mw, net) => `${mw ? `It runs all ${mw} MW` : 'It runs the full campus'}; the grid supplies ${net} MW.`,
    sayHourKeep: (mw, of) => `It runs ${mw}${of ? ` of the ${of}` : ''} MW at this hour.`,
    sayDeepKeep: (mw, of) => `It runs ${mw}${of ? ` of the ${of}` : ''} MW at this hour, and steps down at other hours too.`,
    sayResult0: 'Re-run on the model: 0 people lose power.',
    sayResultN: (n) => `Re-run on the model: ${n} people still lose power.`,
    partly: 'Partly verified: not everyone keeps power',
    keeps: 'Campus kept',
    costLabel: 'Estimated cost',
    costNone: 'Cost not estimated',
    bottomLine: 'Bottom line',
    compared: 'The options, compared',
    bestPick: 'Best pick',
    kept: 'kept',
    noFixWhy: 'No fix reaches them',
    restore: 'Restore in this order',
    lightsBack: 'people back (estimate)',
    aTicker: 'Live facts',
    simTicker: 'SIMULATION · synthetic grid model · every people and cost figure is an estimate',
    campusShare: 'of the first line’s flow is the data center',
    withCampus: 'With the data center',
    withoutCampus: 'Without it',
    limit: 'Limit',
    rank: (n) => `Option ${n}`,
  },
  es: {
    live: 'En vivo',
    paused: 'En pausa',
    tollCost: 'Costo esperado',
    tollTime: 'Tiempo sin luz',
    tollTimeNote: 'Avance rápido hasta el apagón promedio (estimación)',
    tollPeople: 'Personas sin electricidad',
    hoursShort: 'h',
    minShort: 'min',
    range: 'Rango',
    playByPlay: 'Jugada a jugada',
    play: 'Jugada',
    of: 'de',
    transformer: 'Transformador',
    line: 'Línea',
    storm: 'Tormenta',
    ofItsLimit: 'de su límite',
    lose: 'sin luz',
    hit: 'afectadas',
    plus: '+',
    scoreboard: 'Marcador',
    scPeople: 'Personas afectadas (estimación)',
    scMw: 'MW perdidos',
    scLines: 'Líneas caídas',
    scHospitals: 'Hospitales en zonas sin luz',
    step: 'Paso',
    farPast: 'muy por encima de su límite',
    farShort: '>300%',
    restHead: 'Además',
    restCard: (n) => `${n} más`,
    infra: 'Infraestructura crítica',
    infraDown: 'caída',
    hospitalsDark: (n) => `${n} ${n === 1 ? 'hospital' : 'hospitales'} en zonas sin luz (se supone que con respaldo)`,
    subsDark: (n) => `${n} ${n === 1 ? 'subestación' : 'subestaciones'} a oscuras`,
    calloutTransformer: 'Transformador caído',
    calloutLine: 'Línea caída',
    calloutDark: 'Apagón',
    calloutHospitals: 'Hospitales en zonas sin luz (se supone que con respaldo)',
    calloutStorm: 'Daño de la tormenta',
    theProblem: 'El problema',
    slateSub: 'Lo que la red no puede soportar',
    problemPeople: 'Personas sin luz',
    problemCost: 'Costo esperado',
    problemMw: 'MW de carga perdidos',
    problemHours: 'Tiempo sin luz',
    problemLines: 'Líneas disparadas',
    solutions: 'Soluciones',
    option: 'Opción',
    toBuild: (mw) => `Para construir ${mw} MW aquí hay que:`,
    toKeep: 'Para mantener la red en pie hay que:',
    rerun: 'Simulada de nuevo',
    peopleOut: 'Personas sin luz',
    zeroOut: '0 personas pierden la luz',
    peopleOutN: (n) => `${n} personas aún pierden la luz`,
    verifiedEngine: 'Verificada por el motor',
    verifiedAI: 'Propuesta por IA, verificada por el motor',
    aiPlan: 'Plan de IA',
    haveTo: (mw, where) => `Para construir ${mw} MW${where ? ` en ${where}` : ''}, tienes que hacer una de estas`,
    haveToMulti: (n, mw) => `Para construir estos ${n} campus (${mw} MW en total), tienes que hacer una de estas`,
    haveToKeep: 'Para mantener la luz, tienes que hacer una de estas',
    costHigh: (v) => `Costo estimado: hasta ${v}`,
    costHighNote: 'extremo alto de la estimación',
    fullSize: 'Tamaño completo',
    aiFound: (asked, verified) => `La IA propuso ${asked} ${asked === 1 ? 'plan' : 'planes'}; el motor simuló cada uno y verificó ${verified}.`,
    engineFound: (n) => `El motor simuló cada solución en el modelo: ${n} ${n === 1 ? 'funciona' : 'funcionan'}.`,
    aiThinking: 'La IA está proponiendo más planes; el motor comprueba cada uno…',
    frame: 'La IA encuentra las soluciones. El motor físico verifica cada una.',
    aiWork: 'Mira trabajar a la IA',
    aiWorkHead: 'Cómo las encontró la IA: propone, el motor repite el caso, revisa',
    aiWorkHead1: 'Cómo las encontró la IA: propone, el motor repite cada plan',
    aiWorkCount: (asked, verified, rounds) => `${asked} ${asked === 1 ? 'plan' : 'planes'} · ${verified} ${verified === 1 ? 'verificado' : 'verificados'} · ${rounds} ${rounds === 1 ? 'ronda' : 'rondas'}`,
    aiWorkSay: (asked, verified, rounds) => `Cómo las encontró la IA: Gemini propuso ${asked} ${asked === 1 ? 'plan' : 'planes'} en ${rounds} ${rounds === 1 ? 'ronda' : 'rondas'}. El motor repitió cada uno${rounds > 1 ? ', le devolvió lo que seguía fallando' : ''} y verificó ${verified}.`,
    costBar: 'Costo (extremo alto)',
    keptBar: 'Campus conservado',
    sayPlan: (k, n, name, keep) => `Opción ${k} de ${n}: ${name}. ${keep} Si quieres construirlo aquí, tienes que hacer esto.`,
    sayKeepAll: (mw) => `Conserva los ${mw} MW completos.`,
    sayKeep: (mw, of) => `Conserva ${mw} de los ${of} MW.`,
    sayFlexKeep: (mw, except) => `Opera los ${mw} MW completos salvo ${except || 'en el pico'}, sin equipos nuevos.`,
    sayOnsiteKeep: (mw, net) => `${mw ? `Opera los ${mw} MW completos` : 'Opera el campus completo'}; la red aporta ${net} MW.`,
    sayHourKeep: (mw, of) => `Opera ${mw}${of ? ` de los ${of}` : ''} MW a esta hora.`,
    sayDeepKeep: (mw, of) => `Opera ${mw}${of ? ` de los ${of}` : ''} MW a esta hora, y recorta también a otras horas.`,
    sayResult0: 'Simulada de nuevo: 0 personas pierden la luz.',
    sayResultN: (n) => `Simulada de nuevo: ${n} personas siguen sin luz.`,
    partly: 'Verificada en parte: no todos mantienen la luz',
    keeps: 'Campus conservado',
    costLabel: 'Costo estimado',
    costNone: 'Costo sin estimar',
    bottomLine: 'Conclusión',
    compared: 'Las opciones, comparadas',
    bestPick: 'La mejor',
    kept: 'conservado',
    noFixWhy: 'Ninguna solución los alcanza',
    restore: 'Restablecer en este orden',
    lightsBack: 'personas recuperan la luz (estimación)',
    aTicker: 'Datos en vivo',
    simTicker: 'SIMULACRO · modelo sintético de la red · toda cifra de personas y costos es una estimación',
    campusShare: 'del flujo de la primera línea es el centro de datos',
    withCampus: 'Con el centro de datos',
    withoutCampus: 'Sin él',
    limit: 'Límite',
    rank: (n) => `Opción ${n}`,
  },
}

// PRESENT V2 (user, Sat 17:16-17:19): each beat's own picture on the map, the grid's weak point before the campus, the
// fixes placed where they go with what each costs, weighed against the blackout and how often the overload happens.
const LEVEL_ES = { '3 AM': '3 AM', '9 AM': '9 AM', '4 PM': '4 PM', 'in a heat wave': 'en una ola de calor', 'at the height of a heat wave': 'en el pico de una ola de calor' }
// a load level at the end of a sentence: "at 3 AM", "at the 4 PM peak", "in a heat wave" (never "at in a heat wave")
const LEVEL_AT = {
  en: { '3 AM': 'at 3 AM', '9 AM': 'at 9 AM', '4 PM': 'at the 4 PM peak', 'in a heat wave': 'in a heat wave', 'at the height of a heat wave': 'at the height of a heat wave' },
  es: { '3 AM': 'a las 3 AM', '9 AM': 'a las 9 AM', '4 PM': 'en el pico de las 4 PM', 'in a heat wave': 'en una ola de calor', 'at the height of a heat wave': 'en el pico de una ola de calor' },
}
export const atLevel = (name, lang = 'en') => {
  const n = String(name || '')
  const hit = LEVEL_AT[lang === 'es' ? 'es' : 'en'][n]
  if (hit) return hit
  if (lang === 'es') return `al ${n.replace(/of peak$/, 'del pico')}` // "85% of peak"
  return /^\d/.test(n) ? `at ${n}` : n
}
export const joinList = (list, lang = 'en') =>
  list.length > 1 ? `${list.slice(0, -1).join(', ')} ${lang === 'es' ? 'y' : 'and'} ${list[list.length - 1]}` : list[0] || ''
// the levels an operating rule steps down at (the engine's per-level sizes), in words: "at the 4 PM peak and in a heat wave"
export const flexWhen = (flex, lang = 'en') => {
  const steps = flex?.steps || []
  return steps.length ? joinList(steps.map((x) => atLevel(x.name, lang)), lang) : ''
}
const money = (v) => {
  const n = Number(v) || 0
  if (n >= 1e9) return `$${(n / 1e9).toFixed(2).replace(/\.?0+$/, '')}B`
  if (n >= 1e6) return `$${(n / 1e6).toFixed(n >= 1e8 ? 0 : 1).replace(/\.0$/, '')}M`
  if (n >= 1e3) return `$${Math.round(n / 1e3)}k`
  return `$${Math.round(n)}`
}
export const moneyShort = money
export const levelName = (name, lang) => (lang === 'es' ? LEVEL_ES[name] || name : name)
const num = (v) => Math.round(Number(v) || 0).toLocaleString('en-US')

export const P = {
  en: {
    spread: 'The blackout, from where it began',
    origin: 'First failure',
    areasKicker: 'Where the lights went out',
    areaSub: (n) => `${num(n)} without power (estimate)`,
    weakKicker: 'The weak point',
    weakFrame: 'Any big new load here (a data center, a factory, a heat wave) finds it first.',
    gaugeSub: 'today’s grid → with the new load',
    rating: 'rating',
    lastMargin: 'The new load uses up the last margin',
    flowNote: (p) => `${Math.round(p)}% of any new load here flows through it`,
    stormKicker: 'What the storm cut',
    stormCut: (n) => `${num(n)} lines cut by the storm`,
    leadRole: 'Cheapest verified way at full size',
    leadRoleOnly: 'The verified way at full size',
    leadFlex: 'Cheapest verified way: no new equipment',
    leadClosest: 'The closest verified way',
    altRole: 'Another verified way',
    altNoStep: 'If you want no step-downs',
    noEquipment: 'No new equipment',
    total: 'Total, low to high estimate',
    perElement: 'Where it goes and what each costs',
    weighTitle: 'Weighed against what it prevents',
    blackoutBar: 'Blackout if nothing changes',
    fixBar: 'This fix',
    oftenEvery: (low) => `How often: at this size the grid overloads at every load level the model checks, even ${low}. An everyday overload, not a rare event.`,
    oftenPeak: (list) => `How often: only ${list}, the hottest hours of the year.`,
    oftenSome: (list) => `How often: at this size the grid overloads ${list}.`,
    protection: 'The chain reaction assumes each overloaded line trips on its own protection with no operator acting; operators would cut load first. The fix removes the overload itself.',
    flexTitle: 'What the campus runs at, by load level',
    flexFull: 'full size',
    flexExcept: (list) => `full size except ${list}`,
    flexNow: 'this case',
    flexCompute: (mwh, pct, h) => `Its cost is compute, not equipment: at most about ${num(mwh)} MWh a year${pct != null ? ` (${pct}% of its energy)` : ''}, even if it stepped down the full amount in all ${h} hours.`,
    flexAssume: (h) => `Assumption: about ${h} hours of curtailment a year, mostly partial, as reported for Duke University’s 2025 national study of flexible loads (0.25% of their maximum uptime); not measured for this site.`,
    flexTagHead: 'Steps down to',
    moreTitle: 'More options',
    moreNoteUp: 'Also verified on the model: pricier upgrade plans.',
    moreNoteLess: 'Also verified on the model. They build less here, or build it elsewhere.',
    moreNoteBoth: 'Also verified on the model: pricier upgrade plans, and ways that build less here or elsewhere.',
    work: {
      transformer: (o, n) => `Transformer ${num(o)} → ${num(n)} MVA`,
      reconductor: (mi, kv) => `Rebuild ${mi} mi of ${kv} kV line`,
      new_line: (mi, kv) => `New ${kv} kV line, ${mi} mi`,
    },
    compared: 'The options, against the blackout',
    ifNothing: 'If nothing changes',
    keepsAll: 'keeps the full campus',
    keeps: (pct) => `keeps ${pct}%`,
    keepsAtHour: (pct) => `runs ${pct}% at this hour`,
    trigger: 'The trigger',
    triggerTag: (mw) => `${num(mw)} MW data center`,
    hospitalsKicker: 'Hospitals in dark areas',
    hospitalsN: (n) => `${n} ${n === 1 ? 'hospital' : 'hospitals'}`,
    assumedBackup: 'assumed on backup',
    costBlackout: (v) => `Blackout: up to ${v}`,
    costFix: (v) => `Upgrades: up to ${v}`,
    noFixReach: 'No fix reaches them',
    sidebarHint: 'Ask anything about this case. The answers use the engine’s numbers.',
    options: 'Options',
    moreOptions: 'More options',
    fewerOptions: 'Fewer options',
    version: 'Version',
    full: 'Full',
    shortV: 'Short',
    view: 'View',
    // DISTINCT OPTIONS (user, Sat 19:12): what kind of fix each option is
    kindWeak: 'Upgrade the weak point',
    kindGrid: 'Strengthen the grid',
    kindOther: 'A different set of upgrades',
    kindCheaper: 'The same upgrades, for less',
    kindOnsite: 'Power of its own',
    kindFlex: 'An operating rule, no new equipment',
    kindDeep: 'An operating rule, with deep step-downs',
    cheapestFull: 'cheapest verified at full size',
    onsiteKeeps: (net) => `runs the full campus; the grid supplies ${net} MW`,
    onsitePin: (mw) => `${mw} MW on site`,
    onsitePinSub: (net) => `grid supplies ${net} MW`,
    variants: (n, ai) => `${ai ? 'Gemini found' : 'Also verified:'} ${n} ${n === 1 ? 'variant' : 'variants'} of this plan`,
    // a deck without the backend's own line (variants_how): what they share with the plan, loosely but truly
    variantsHow: (n, pricier) => (pricier ? (n === 1 ? 'Mostly the same upgrades; verified, and it costs more' : 'Mostly the same upgrades; each verified, each costs more') : 'Mostly the same upgrades, about the same price; each verified'),
    variantsPlus: (label) => `+ ${label}`,
    compareHead: 'The options, side by side',
    howAi: 'How the AI found them',
    howAiShort: 'How the AI found them',
    tabAsk: 'Ask',
    tabAi: 'How the AI found them',
    aiPanelTitle: 'How the AI found these plans',
    aiPanelLead: 'Gemini proposes a whole plan; the physics engine re-runs the case with it; what still overloads goes back to Gemini. Only plans the engine verifies reach the options.',
    aiPanelWhere: (n, k) => `In the options: ${n} verified ${n === 1 ? 'plan' : 'plans'}, folded into option ${k} as ${n === 1 ? 'a variant' : 'variants'}.`,
    aiPanelWhereOwn: (k) => `In the options: option ${k} is Gemini’s own plan.`,
    aiPanelOff: 'No AI run for this case: every option here is the engine’s own.',
    aiPanelEvery: (n) => `Show every step (${n})`,
    aiPanelFewer: 'Show the key steps',
    closeSide: 'Close the side panel',
    // SOLUTIONS, SIMPLE (user, Sat 20:31): each option in five plain lines, in this order
    plain: { what: 'What', where: 'Where', cost: 'Cost', prevents: 'Prevents', time: 'Time' },
    fullSolution: 'The full solution',
    source: 'source',
    fullSolutionHint: 'This incident on Strengthen: every verified option in depth, on the map',
  },
  es: {
    spread: 'El apagón, desde donde empezó',
    origin: 'Primera falla',
    areasKicker: 'Dónde se fue la luz',
    areaSub: (n) => `${num(n)} sin luz (estimación)`,
    weakKicker: 'El punto débil',
    weakFrame: 'Cualquier carga grande nueva aquí (un centro de datos, una fábrica, una ola de calor) lo encuentra primero.',
    gaugeSub: 'red de hoy → con la nueva carga',
    rating: 'capacidad',
    lastMargin: 'La nueva carga agota el último margen',
    flowNote: (p) => `El ${Math.round(p)}% de cualquier carga nueva aquí pasa por ahí`,
    stormKicker: 'Lo que cortó la tormenta',
    stormCut: (n) => `${num(n)} líneas cortadas por la tormenta`,
    leadRole: 'La manera verificada más barata a tamaño completo',
    leadRoleOnly: 'La manera verificada a tamaño completo',
    leadFlex: 'La manera verificada más barata: sin equipos nuevos',
    leadClosest: 'La manera verificada más cercana',
    altRole: 'Otra manera verificada',
    altNoStep: 'Si no quieres recortes',
    noEquipment: 'Sin equipos nuevos',
    total: 'Total, estimación baja a alta',
    perElement: 'Dónde va y cuánto cuesta cada parte',
    weighTitle: 'Frente a lo que evita',
    blackoutBar: 'Apagón si nada cambia',
    fixBar: 'Esta solución',
    oftenEvery: (low) => `Con qué frecuencia: con este tamaño la red se sobrecarga en todos los niveles de carga del modelo, incluso ${low}. Una sobrecarga diaria, no un caso raro.`,
    oftenPeak: (list) => `Con qué frecuencia: solo ${list}, las horas más calurosas del año.`,
    oftenSome: (list) => `Con qué frecuencia: con este tamaño la red se sobrecarga ${list}.`,
    protection: 'La reacción en cadena supone que cada línea sobrecargada se dispara por su propia protección sin que actúe un operador; los operadores cortarían carga antes. La solución elimina la sobrecarga en sí.',
    flexTitle: 'Lo que opera el campus, por nivel de carga',
    flexFull: 'tamaño completo',
    flexExcept: (list) => `tamaño completo salvo ${list}`,
    flexNow: 'este caso',
    flexCompute: (mwh, pct, h) => `Su costo es cómputo, no equipos: como mucho unos ${num(mwh)} MWh al año${pct != null ? ` (${pct}% de su energía)` : ''}, aun si recortara todo el escalón en las ${h} horas.`,
    flexAssume: (h) => `Supuesto: unas ${h} horas de recorte al año, casi siempre parcial, según lo publicado sobre el estudio nacional de 2025 de la Universidad de Duke sobre cargas flexibles (0,25% de su tiempo máximo de operación); no medido para este sitio.`,
    flexTagHead: 'Recorta a',
    moreTitle: 'Más opciones',
    moreNoteUp: 'También verificadas en el modelo: planes de refuerzo más caros.',
    moreNoteLess: 'También verificadas en el modelo. Construyen menos aquí, o lo construyen en otro lugar.',
    moreNoteBoth: 'También verificadas en el modelo: planes de refuerzo más caros, y maneras que construyen menos aquí o en otro lugar.',
    work: {
      transformer: (o, n) => `Transformador ${num(o)} → ${num(n)} MVA`,
      reconductor: (mi, kv) => `Reconstruir ${mi} mi de línea de ${kv} kV`,
      new_line: (mi, kv) => `Línea nueva de ${kv} kV, ${mi} mi`,
    },
    compared: 'Las opciones, frente al apagón',
    ifNothing: 'Si nada cambia',
    keepsAll: 'conserva el campus completo',
    keeps: (pct) => `conserva el ${pct}%`,
    keepsAtHour: (pct) => `opera al ${pct}% a esta hora`,
    trigger: 'El detonante',
    triggerTag: (mw) => `Centro de datos de ${num(mw)} MW`,
    hospitalsKicker: 'Hospitales en zonas sin luz',
    hospitalsN: (n) => `${n} ${n === 1 ? 'hospital' : 'hospitales'}`,
    assumedBackup: 'se supone que con respaldo',
    costBlackout: (v) => `Apagón: hasta ${v}`,
    costFix: (v) => `Refuerzos: hasta ${v}`,
    noFixReach: 'Ninguna solución los alcanza',
    sidebarHint: 'Pregunta lo que quieras sobre este caso. Las respuestas usan las cifras del motor.',
    options: 'Opciones',
    moreOptions: 'Más opciones',
    fewerOptions: 'Menos opciones',
    version: 'Versión',
    full: 'Completa',
    shortV: 'Corta',
    view: 'Vista',
    kindWeak: 'Reforzar el punto débil',
    kindGrid: 'Reforzar la red',
    kindOther: 'Otro conjunto de refuerzos',
    kindCheaper: 'Los mismos refuerzos, por menos',
    kindOnsite: 'Energía propia',
    kindFlex: 'Una regla de operación, sin equipos nuevos',
    kindDeep: 'Una regla de operación, con recortes profundos',
    cheapestFull: 'la más barata verificada a tamaño completo',
    onsiteKeeps: (net) => `opera el campus completo; la red aporta ${net} MW`,
    onsitePin: (mw) => `${mw} MW propios`,
    onsitePinSub: (net) => `la red aporta ${net} MW`,
    variants: (n, ai) => `${ai ? 'Gemini encontró' : 'También verificadas:'} ${n} ${n === 1 ? 'variante' : 'variantes'} de este plan`,
    variantsHow: (n, pricier) => (pricier ? (n === 1 ? 'Casi los mismos refuerzos; verificada, y cuesta más' : 'Casi los mismos refuerzos; todas verificadas, todas cuestan más') : 'Casi los mismos refuerzos, por un precio parecido; todas verificadas'),
    variantsPlus: (label) => `+ ${label}`,
    compareHead: 'Las opciones, lado a lado',
    howAi: 'Cómo las encontró la IA',
    howAiShort: 'Cómo las encontró la IA',
    tabAsk: 'Preguntar',
    tabAi: 'Cómo las encontró la IA',
    aiPanelTitle: 'Cómo encontró la IA estos planes',
    aiPanelLead: 'Gemini propone un plan completo; el motor físico repite el caso con él; lo que sigue sobrecargado vuelve a Gemini. Solo los planes que el motor verifica llegan a las opciones.',
    aiPanelWhere: (n, k) => `En las opciones: ${n} ${n === 1 ? 'plan verificado' : 'planes verificados'}, incluidos en la opción ${k} como ${n === 1 ? 'variante' : 'variantes'}.`,
    aiPanelWhereOwn: (k) => `En las opciones: la opción ${k} es el plan de Gemini.`,
    aiPanelOff: 'No hubo trabajo de la IA en este caso: todas las opciones son del motor.',
    aiPanelEvery: (n) => `Ver cada paso (${n})`,
    aiPanelFewer: 'Ver los pasos clave',
    closeSide: 'Cerrar el panel lateral',
    plain: { what: 'Qué', where: 'Dónde', cost: 'Costo', prevents: 'Evita', time: 'Plazo' },
    fullSolution: 'La solución completa',
    source: 'fuente',
    fullSolutionHint: 'Este incidente en Reforzar la red: cada opción verificada en detalle, en el mapa',
  },
}

// What each option asks for ("you have to ..."), by family; the engine's own list (option.must) wins.
export const MUST = {
  en: {
    upgrade: (l) => `Upgrade ${l.label}: ${Math.round(l.old_mva).toLocaleString('en-US')} to ${Math.round(l.new_mva).toLocaleString('en-US')} MVA`,
    shrink: (from, to) => [`Cut the campus from ${from} MW to ${to} MW`, `Accept about ${Math.round((to / from) * 100)}% of the planned size`],
    move: (town) => [`Build it at a ${town} substation instead`, 'Use a site with room on its lines'],
    flexible: (mw) => [`Agree to curtail to ${mw} MW at the peak`, 'Run at full size in the quieter hours'],
    onsite: (gen, net) => [`Add ${gen} MW of on-site generation`, `Let the grid supply only ${net} MW`],
    combo: (mw) => [`Shrink the campus to ${mw} MW`],
    remove: () => ['Do not build the data center at this site'],
  },
  es: {
    upgrade: (l) => `Mejorar ${l.label.replace(/^the /, '')}: ${Math.round(l.old_mva).toLocaleString('en-US')} a ${Math.round(l.new_mva).toLocaleString('en-US')} MVA`,
    shrink: (from, to) => [`Reducir el campus de ${from} MW a ${to} MW`, `Aceptar cerca del ${Math.round((to / from) * 100)}% del tamaño planeado`],
    move: (town) => [`Construirlo en una subestación de ${town}`, 'Usar un sitio con espacio en sus líneas'],
    flexible: (mw) => [`Aceptar recortar a ${mw} MW en el pico`, 'Operar a tamaño completo en las horas tranquilas'],
    onsite: (gen, net) => [`Añadir ${gen} MW de generación propia`, `Que la red suministre solo ${net} MW`],
    combo: (mw) => [`Reducir el campus a ${mw} MW`],
    remove: () => ['No construir el centro de datos en este sitio'],
  },
}

export const OPTION_NAME = {
  en: {
    upgrade: (mw) => `Strengthen the grid, keep all ${mw} MW`,
    shrink: (mw) => `Build smaller: ${mw} MW`,
    move: () => 'Build it somewhere with room',
    flexible: (mw) => `Make it flexible: curtail to ${mw} MW at the peak`,
    onsite: (gen) => `Generate ${gen} MW on site`,
    combo: (mw) => `Build ${mw} MW and upgrade the weak link`,
    agentic: () => 'AI plan: strengthen the grid',
    remove: () => 'Do not build it here',
    other: () => 'Another fix',
  },
  es: {
    upgrade: (mw) => `Reforzar la red y mantener los ${mw} MW`,
    shrink: (mw) => `Construir más pequeño: ${mw} MW`,
    move: () => 'Construirlo donde haya espacio',
    flexible: (mw) => `Hacerlo flexible: recortar a ${mw} MW en el pico`,
    onsite: (gen) => `Generar ${gen} MW en el sitio`,
    combo: (mw) => `Construir ${mw} MW y reforzar el punto débil`,
    agentic: () => 'Plan de IA: reforzar la red',
    remove: () => 'No construirlo aquí',
    other: () => 'Otra solución',
  },
}
