"""Smoke checks for Negotiate (backend/negotiate.py). Loaded by smoke_test.py.

ctx: check(name, fn), request(method, path, data=None, headers=None, expect=200).

The HTTP checks ask for the plain (rule-based) negotiation with ai=false, so a smoke run never spends Gemini quota; every
turn's verdict is recomputed here from the agreement, estimate and project routes (not from negotiate.py's code). The
verifier and the agentic loop run in-process: forged invalid proposals, a scripted stand-in for Gemini whose first
proposal the verifier rejects and whose revision it accepts (the findings must reach the agent's next prompt), and the
labeled fallback with GEMINI_API_KEY blank."""

import asyncio
import os
import sys
from datetime import date
from pathlib import Path

DISCLAIMER = (
    "Draft for discussion, generated by Overload from the two public filings; not an agreement between, or endorsed by, "
    "either utility."
)
SECOND = "DESC-6810O~GA-21116"  # a pair whose filed windows share months after today (Jan-Dec 2028: DESC's money is filed in 2028)


def _ym(iso: str) -> tuple[int, int]:
    y, m = iso.split("-")[:2]
    return int(y), int(m)


def register(ctx):
    state = {}

    def top_overlap():
        if "id" not in state:
            o = ctx.request("GET", "/api/gridlock/opportunities?limit=1")
            assert o["opportunities"], "no opportunity to negotiate"
            state["id"] = o["opportunities"][0]["id"]
        return state["id"]

    def plain(oid, extra=""):
        return ctx.request("POST", f"/api/negotiate/{oid}?ai=false{extra}")

    def shape():
        oid = top_overlap()
        r = plain(oid)
        state["top"] = r
        assert r["overlap_id"] == oid and r["by"] == "fallback" and r["fallback_reason"] == "Plain version requested", (r["by"], r["fallback_reason"])
        assert r["disclaimer"] == DISCLAIMER and r["calls"] == 0 and r["max_calls"] <= 8 and r["max_rounds"] == 3, r
        assert [a["side"] for a in r["agents"]] == ["a", "b"] and r["agents"][0]["utility"] != r["agents"][1]["utility"], r["agents"]
        for a in r["agents"]:
            assert "AI agent reading" in a["represents"] and a["utility_name"] in a["represents"], a["represents"]
            assert a["not_the_utility"].startswith("Not ") and a["filing"] and a["source"]["kind"] == "filing", a
        assert 2 <= len(r["turns"]) <= 8, len(r["turns"])
        for n, t in enumerate(r["turns"], 1):
            assert t["n"] == n and t["agent"] in ("a", "b") and 1 <= t["round"] <= 3 and t["kind"] in ("propose", "counter", "accept", "revise"), t
            assert isinstance(t["verdict"]["ok"], bool) and isinstance(t["verdict"]["findings"], list), t["verdict"]
            assert {d["k"] for d in t["plain"]} == {"window", "scope", "split"}, t["plain"]
        o = r["outcome"]
        assert o["agreed"] is True and o["verified"] is True and o["terms"], o
        assert r["turns"][-1]["kind"] == "accept" and r["turns"][-1]["verdict"]["ok"], r["turns"][-1]
        assert sum(o["terms"]["split"]["shares"]) == 100, o["terms"]["split"]
        if not o["terms"]["joint_window"]:
            assert r["bounds"]["feasible"] is None and o["next"] and "current status" in o["next"], (r["bounds"], o["next"])

    def verdicts_recomputed():
        """Each turn's window, scope and split checked again from the agreement, estimate and projects routes."""
        for oid in (top_overlap(), SECOND):
            r = state["top"] if oid == state.get("id") and "top" in state else plain(oid)
            d = ctx.request("GET", f"/api/agreement/{oid}?ai=false")
            est = ctx.request("GET", f"/api/gridlock/estimate/{oid}")
            items = {it["id"]: it for it in est["items"]}
            projs = {p["side"]: p for p in d["overlap"]["projects"]}
            now = _ym(d["draft"]["joint_window"]["as_of"])
            wins = {s: (_ym(p["window"]["start"]), _ym(p["window"]["end"])) if p.get("window") else None for s, p in projs.items()}
            lo = max([w[0] for w in wins.values() if w] + [now]) if all(wins.values()) else None
            hi = min(w[1] for w in wins.values() if w) if all(wins.values()) else None
            feasible = (lo, hi) if lo and hi and lo <= hi else None
            ma, mb = projs["a"].get("miles"), projs["b"].get("miles")
            shares = {"equal": [50, 50]}
            if ma and mb:
                pa_ = round(100 * ma / (ma + mb))
                shares["by_length"] = [pa_, 100 - pa_]
            if projs["a"]["kv"] and projs["b"]["kv"]:
                ka, kb = max(projs["a"]["kv"]), max(projs["b"]["kv"])
                pk = round(100 * ka / (ka + kb))
                shares["by_kv"] = [pk, 100 - pk]
            assert {x["id"]: x["shares"] for x in r["rules"]} == shares, (r["rules"], shares)
            for t in r["turns"]:
                p = t["proposal"]
                ok = True
                jw = p["joint_window"]
                if jw:
                    s, e = _ym(jw["start"]), _ym(jw["end"])
                    ok &= bool(feasible) and feasible[0] <= s <= e <= feasible[1]
                else:
                    ok &= feasible is None
                ok &= bool(p["scope"]) and all(i in items for i in p["scope"]) and not p.get("scope_unknown")
                sp = p["split"]
                ok &= sp["rule"] in shares and sum(sp["shares"]) == 100 and list(sp["shares"]) == shares[sp["rule"]]
                assert ok == t["verdict"]["ok"], (oid, t["n"], p, t["verdict"])
            terms = r["outcome"]["terms"]
            lo_sum = sum(items[i["id"]]["low"] for i in terms["scope"] if items[i["id"]]["unit"] == "USD")
            hi_sum = sum(items[i["id"]]["high"] for i in terms["scope"] if items[i["id"]]["unit"] == "USD")
            assert terms["savings"]["low"] == lo_sum and terms["savings"]["high"] == hi_sum, (terms["savings"], lo_sum, hi_sum)
            if oid == SECOND:
                assert feasible and terms["joint_window"], (feasible, terms["joint_window"])

    def unknown_is_404_bad_is_422():
        ctx.request("POST", "/api/negotiate/NOPE-1~NADA-2?ai=false", expect=404)
        ctx.request("POST", "/api/negotiate/no-tilde?ai=false", expect=404)
        p = ctx.request("GET", "/api/gridlock/projects")["projects"]
        desc = [x["id"] for x in p if x["utility"] == "DESC" and x.get("geometry")][:2]
        if len(desc) == 2:
            ctx.request("POST", f"/api/negotiate/{desc[0]}~{desc[1]}?ai=false", expect=404)
        oid = top_overlap()
        ctx.request("POST", f"/api/negotiate/{oid}?ai=false&lang=fr", expect=422)
        ctx.request("POST", f"/api/negotiate/{oid}?ai=false&window_months=999", expect=422)
        ctx.request("POST", f"/api/negotiate/{'x' * 250}~y?ai=false", expect=422)
        ctx.request("GET", f"/api/agreement/{oid}?ai=false&negotiated=maybe", expect=422)
        ctx.request("GET", "/api/agreement/NOPE-1~NADA-2?ai=false&negotiated=plain", expect=404)
        live = ctx.request("GET", f"/api/negotiate/{oid}/live")
        assert live == {"running": False}, live

    def cached_second_time():
        oid = top_overlap()
        first = plain(oid, "&window_months=36")
        again = plain(oid, "&window_months=36")
        assert again["cached"] is True and again["turns"] == first["turns"] and again["outcome"] == first["outcome"], "the cached negotiation differs"

    def terms_feed_the_draft():
        for oid in (top_overlap(), SECOND):
            r = plain(oid)
            t = r["outcome"]["terms"]
            doc = ctx.request("GET", f"/api/agreement/{oid}?ai=false&negotiated=plain")
            assert doc["negotiated"]["applied"] is True and doc["negotiated"]["by"] == "plain", doc["negotiated"]
            assert doc["verified"] is True, doc["rejected"]
            d = doc["draft"]
            assert d["negotiated"] and "verified against the filings" in d["negotiated"]["text"], d["negotiated"]
            assert [s["pct"] for s in d["cost_split"]["shares"]] == t["split"]["shares"], (d["cost_split"], t["split"])
            assert [i["id"] for i in d["savings"]["items"]] == [i["id"] for i in t["scope"]], d["savings"]["items"]
            assert any("verified against the filings" in c["text"] for c in d["conditions"]), d["conditions"]
            if t["joint_window"]:
                assert d["joint_window"]["negotiated"]["start"].startswith(t["joint_window"]["start"]), d["joint_window"]
                assert d["joint_window"]["text"].startswith("Proposed joint window"), d["joint_window"]["text"]
            else:
                assert d["joint_window"]["negotiated"] is None, d["joint_window"]
            plain_doc = ctx.request("GET", f"/api/agreement/{oid}?ai=false")
            assert plain_doc["negotiated"] is None and plain_doc["draft"]["negotiated"] is None, plain_doc["negotiated"]

    # ------------------------------------------------------------------ in-process

    def in_process(fn, key=None):
        def run():
            sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
            os.environ.setdefault("JWT_SECRET", "smoke-check-only-not-a-secret")  # llm.py imports auth.py; this process only
            try:
                import negotiate
            except ImportError as e:  # a deployed run without the backend folder on the path
                raise AssertionError(f"negotiate.py not importable here: {e}") from e
            saved = os.environ.get("GEMINI_API_KEY")
            os.environ["GEMINI_API_KEY"] = key if key is not None else ""
            try:
                fn(negotiate)
            finally:
                if saved is None:
                    os.environ.pop("GEMINI_API_KEY", None)
                else:
                    os.environ["GEMINI_API_KEY"] = saved

        return run

    def forged_turns_rejected(ng):
        case = ng._case(SECOND, 24)
        r = case["rules_by_id"]["by_length"]["shares"]

        def forge(**kw):
            base = {"joint_window": {"start": "2028-01", "end": "2028-12"}, "scope": ["mobilization"],
                    "split": {"rule": "by_length", "a_pct": r[0], "b_pct": r[1]}, "concerns": [], "note": "", "accept": False}
            base.update(kw)
            return base

        v, _ = ng.verify(forge(), case)
        assert v["ok"], v
        bad = {
            "window outside the filings": (forge(joint_window={"start": "2026-10", "end": "2030-06"}), "outside DESC's filed build window"),
            "window in the past": (forge(joint_window={"start": "2025-06", "end": "2027-06"}), "before today"),
            "split not summing to 100": (forge(split={"rule": "by_length", "a_pct": 60, "b_pct": 50}), "not 100"),
            "shares not the rule's": (forge(split={"rule": "equal", "a_pct": 40, "b_pct": 60}), "not 40 % and 60 %"),
            "a rule that isn't allowed": (forge(split={"rule": "by_cost", "a_pct": 50, "b_pct": 50}), "not an allowed split rule"),
            "an unknown scope id": (forge(scope=["mobilization", "helicopters"]), "'helicopters' is not one of the estimate's items"),
            "an invented number": (forge(concerns=["Sharing would cut 37 truck trips."]), "number 37 is not in the facts"),
            "an invented dollar amount": (forge(note="Sharing crews could save $412K."), "money figure 412 is not one of the facts' dollar amounts"),
            "speaking for a utility": (forge(note="Georgia Power wants the crews first."), "speaks for a utility"),
            "writing as 'we'": (forge(note="We accept the window."), "third person"),
            "no window when the filings leave one": (forge(joint_window={"start": "", "end": ""}), "propose a window inside it"),
        }
        for name, (raw, want) in bad.items():
            v, _ = ng.verify(raw, case)
            assert not v["ok"] and any(want in f for f in v["findings"]), (name, v["findings"])
        # the top pair's shared months have passed: a window is rejected, none is right
        past = ng._case("DESC-6852~GA-21116", 24, as_of=date(2026, 9, 26))
        v, _ = ng.verify(forge(joint_window={"start": "2026-10", "end": "2027-03"}), past)
        assert not v["ok"] and any("ended before today" in f for f in v["findings"]), v
        v, _ = ng.verify(forge(joint_window={"start": "", "end": ""}, split={"rule": "equal", "a_pct": 50, "b_pct": 50}), past)
        assert v["ok"], v

    def agentic_loop(ng):
        """A stand-in for Gemini: agent A's first proposal breaks the filings, the verifier rejects it, the findings reach
        A's next prompt, A revises; B (whose filing supports paying 50 %) tries to accept 73 % in round 1 and is held to
        its goal, so it counters; they trade until A accepts B's split in the last round. The loop, not Gemini, is under test."""
        import llm

        prompts = []
        case = ng._case(SECOND, 24)
        assert case["conflict"]["split"], case["goals"]  # 46 kV / 4.5 mi against 230 kV / 12.3 mi: the goals conflict
        by_len = case["rules_by_id"]["by_length"]["shares"]
        win = {"start": "2028-02", "end": "2028-11"}
        good = {"joint_window": win, "scope": ["mobilization"], "split": {"rule": "by_length", "a_pct": by_len[0], "b_pct": by_len[1]},
                "concerns": ["As filed, the build window runs Jan 2028 to Dec 2028."], "note": "This agent proposes a window inside the filing.", "accept": False}
        equal = {**good, "split": {"rule": "equal", "a_pct": 50, "b_pct": 50}, "concerns": [], "note": "This agent counters with an equal split."}

        async def fake(prompt, system=None, fallback=None, timeout=None, schema=None, cache=True, surface=None, model=None, image=None):
            prompts.append(prompt)
            assert surface == "negotiation" and schema and "never speak for it" in system and "YOUR GOAL" in prompt
            rejected = "THE PIPELINE REJECTED YOUR LAST PROPOSAL" in prompt
            if prompt.startswith("You are agent A"):
                if "Round 1 of" in prompt and not rejected:
                    return {**good, "joint_window": {"start": "2029-01", "end": "2030-06"}}, False  # outside DESC's filed window
                if "Round 3 of" in prompt:
                    return {**equal, "note": "This agent accepts the proposal on the table.", "accept": True}, False
                return good, False
            if "Round 1 of" in prompt and not rejected:
                return {**good, "concerns": [], "note": "This agent accepts the proposal on the table.", "accept": True}, False
            return equal, False

        saved = llm.complete_json
        llm.complete_json = fake
        try:
            out = asyncio.run(ng.run_case(SECOND, 24, "en", True, as_of=date(2026, 9, 26)))
        finally:
            llm.complete_json = saved
        assert out["by"] == "gemini" and out["calls"] == 7 and len(out["turns"]) == 7, (out["by"], out["calls"], out["fallback_reason"], len(out["turns"]))
        t = out["turns"]
        assert not t[0]["verdict"]["ok"] and any("outside DESC's filed build window" in f for f in t[0]["verdict"]["findings"]), t[0]["verdict"]
        assert t[1]["revision"] and t[1]["kind"] == "revise" and t[1]["verdict"]["ok"], t[1]
        assert "THE PIPELINE REJECTED YOUR LAST PROPOSAL" in prompts[1] and "outside DESC's filed build window" in prompts[1], prompts[1][-600:]
        # B tried to accept 73 % in round 1: held to its goal (at most 50 %), it counters
        assert t[2]["agent"] == "b" and not t[2]["verdict"]["ok"] and any("goes past this agent's goal" in f for f in t[2]["verdict"]["findings"]), t[2]["verdict"]
        assert t[3]["agent"] == "b" and t[3]["verdict"]["ok"] and t[3]["proposal"]["split"]["rule"] == "equal", t[3]
        assert t[6]["agent"] == "a" and t[6]["kind"] == "accept" and t[6]["round"] == 3 and t[6]["verdict"]["ok"], t[6]
        o = out["outcome"]
        assert o["agreed"] and o["verified"] and o["terms"]["joint_window"] == win and o["terms"]["split"]["rule"] == "equal", o
        assert out["conflict"]["split"] and out["goals"]["b"]["cap_pct"] == 50 and "50 %" in out["goals"]["b"]["text"], out["goals"]
        # agent B's prompt carries only B's own filing (plus the shared facts), never A's filing facts
        b_prompt = next(x for x in prompts if x.startswith("You are agent B"))
        mine = b_prompt.split("YOUR FILING")[1].split("SHARED FACTS")[0]
        assert "- b." in mine and "- a." not in mine, mine[:400]

    def format_retries_hidden(ng):
        """A turn rejected only for its format (a window not written as months) and then revised by the same agent is left
        out of the trace a person reads (kept in raw_turns); a substantive rejection stays."""
        def turn(n, agent, ok, findings, revision=False, kind="propose"):
            return {"n": n, "round": 1, "agent": agent, "kind": kind, "revision": revision, "verdict": {"ok": ok, "findings": findings, "notes": []}}
        raw = [turn(1, "a", False, ["the window 2028/02 to 2028/11 is not a pair of months (YYYY-MM)"]),
               turn(2, "a", True, [], True, "revise"),
               turn(3, "b", False, ["concern 1: number 37 is not in the facts"], False, "counter"),
               turn(4, "b", True, [], True, "revise")]
        pub = ng.public_turns(raw)
        assert [x["raw_n"] for x in pub] == [2, 3, 4] and [x["n"] for x in pub] == [1, 2, 3], pub
        assert pub[0]["kind"] == "propose" and not pub[0]["revision"], pub[0]
        assert pub[2]["revision"] and pub[2]["kind"] == "revise", pub[2]

    def fallback_without_a_key(ng):
        out = asyncio.run(ng.run_case(SECOND, 24, "es", True, as_of=date(2026, 1, 15)))  # a date no live run has: never an llm.py cache hit
        assert out["by"] == "fallback" and out["fallback_reason"] == "Gemini not configured", (out["by"], out["fallback_reason"])
        assert out["outcome"]["agreed"] and out["outcome"]["verified"] and all(t["verdict"]["ok"] for t in out["turns"]), out["outcome"]
        again = asyncio.run(ng.run_case(SECOND, 24, "es", True, as_of=date(2026, 1, 15)))
        assert again["cached"] is False, "a transient Gemini miss must not be cached"

    def nothing_to_negotiate():
        # a pair whose windows share no months at a distance where only crews could be shared: the estimate has no item,
        # so no agent is asked; the reason says what would need a shared window, and the draft says nothing is estimated
        rows = ctx.request("GET", "/api/gridlock/overlaps?limit=2000")["overlaps"]
        oid = None
        for r in rows:
            if r["same_window"] is False and r["tier"] == "crews":
                e = ctx.request("GET", f"/api/gridlock/estimate/{r['id']}")
                if not e["items"]:
                    oid = r["id"]
                    break
        assert oid, "no pair with nothing estimated"
        r = ctx.request("POST", f"/api/negotiate/{oid}?ai=true")
        o = r["outcome"]
        assert r["by"] == "none" and r["calls"] == 0 and r["turns"] == [], (r["by"], r["calls"], len(r["turns"]))
        assert o["nothing"] is True and o["agreed"] is False and "Nothing to propose" in o["reason"] and "share months" in o["reason"], o
        d = ctx.request("GET", f"/api/agreement/{oid}?ai=false")
        assert d["draft"]["savings"]["items"] == [] and d["draft"]["savings"]["left_out"], d["draft"]["savings"]
        assert "Nothing is estimated" in d["draft"]["summary"]["text"], d["draft"]["summary"]["text"]

    def hear_the_negotiation():
        """Hear the negotiation: every verified turn carries a voice key (agent A presenter, B analyst, the closing summary
        presenter), the spoken text is the turn's own words (its concerns and note; nothing added), a rejected turn is not
        read aloud, and each key is registered with voice.py (200 audio, or 503 without a key: never 409 unknown)."""
        import re as _re
        oid = top_overlap()
        for lang in ("en", "es"):
            r = ctx.request("POST", f"/api/negotiate/{oid}?ai=false&lang={lang}")
            v = r["voice"]
            assert v["roles"] == {"a": "presenter", "b": "analyst", "summary": "presenter"} and v["attribution"] == "Voice: ElevenLabs", v
            spoken = []
            for t in r["turns"]:
                tv = t["voice"]
                if not t["verdict"]["ok"]:
                    assert tv is None, "a rejected turn must not be read aloud"
                    continue
                p = t["proposal"]
                assert tv and _re.fullmatch(r"[0-9a-f]{32}", tv["key"]) and tv["lang"] == lang, tv
                assert tv["role"] == ("presenter" if t["agent"] == "a" else "analyst") and tv["side"] == t["agent"], (tv, t["agent"])
                words = [str(c) for c in p["concerns"]] + ([p["note"]] if p["note"] else [])
                if words:  # its own words, verbatim (a full stop may be added), and no figure that is not in them
                    assert all(w.rstrip(".!?… ") in tv["text"] for w in words), (tv["text"], words)
                    assert _re.findall(r"\d+", tv["text"]) == _re.findall(r"\d+", " ".join(words)), (tv["text"], words)
                else:  # an acceptance with no words of its own: one fixed lead-in with no figure
                    assert not _re.search(r"\d", tv["text"]) and len(tv["text"]) < 60, tv["text"]
                spoken.append(tv)
            assert spoken, "no turn can be heard"
            sm = v["summary"]
            assert sm and sm["role"] == "presenter" and sm["side"] == "summary" and _re.fullmatch(r"[0-9a-f]{32}", sm["key"]), sm
            assert str(r["outcome"]["round"]) in sm["text"] and ("re-checked" in sm["text"] or lang == "es"), sm["text"]
            spoken.append(sm)
            # a registered key is 200 (audio) or 503 (no voice key here), never 409 "unknown"; a server WITH a key would render
            # (spend credits) on this call, so it is only asked without one
            if not ctx.request("GET", "/api/voice/status")["configured"]:
                for tv in spoken[:2] + [sm]:
                    try:
                        ctx.request("POST", "/api/voice/segment", {"key": tv["key"]})
                    except AssertionError as e:
                        assert "503" in str(e) and "Voice not configured" in str(e), f"a registered key must be 200 or 503: {e}"

    ctx.check("negotiate: the plain negotiation of the top opportunity has two filing-reading agents, verified turns and agreed terms", shape)
    ctx.check("negotiate: a pair with nothing in its estimate (no shared window, crews-tier) has nothing to negotiate: no agent "
              "asked, the reason said, the draft says nothing is estimated", nothing_to_negotiate)
    ctx.check("negotiate: every turn's verdict recomputed from the agreement, estimate and project routes (window, scope, split)", verdicts_recomputed)
    ctx.check("negotiate: an unknown or same-utility pair is a 404; bad lang, window or id is a 422; no live run", unknown_is_404_bad_is_422)
    ctx.check("negotiate: the same negotiation again is served from the cache", cached_second_time)
    ctx.check("negotiate: the agreed terms feed the drafted agreement (split, scope, window) and the draft says they were negotiated", terms_feed_the_draft)
    ctx.check("negotiate: the verifier rejects a window outside the filings, a split off 100, an unknown scope id, an invented number, speaking for a utility",
              in_process(forged_turns_rejected))
    ctx.check("negotiate: a rejected turn's findings reach the agent's next prompt, its revision passes; an agent is held to its "
              "filing's goal before the last round, so real counter-offers happen; they settle in the last round",
              in_process(agentic_loop, key="smoke-fake-key-never-sent"))
    ctx.check("negotiate: format-only retries are hidden from the trace a person reads (kept in raw_turns); substantive rejections stay",
              in_process(format_retries_hidden))
    ctx.check("negotiate: with GEMINI_API_KEY blank the labeled plain version runs (and is not cached)", in_process(fallback_without_a_key))
    ctx.check("negotiate: Hear the negotiation: verified turns carry voice keys (A presenter, B analyst, summary presenter), the spoken text is "
              "the turn's own words with no added figure, a rejected turn is not read aloud, keys are registered with voice.py (200 or 503, never 409)",
              hear_the_negotiation)
